/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    sources: Source;
    'calculator-rule-sets': CalculatorRuleSet;
    scenarios: Scenario;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'calculator-rule-sets': CalculatorRuleSetsSelect<false> | CalculatorRuleSetsSelect<true>;
    scenarios: ScenariosSelect<false> | ScenariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'kk' | 'kk'[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'kk';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor' | 'reviewer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Тұрақты URL: латын әріптері, сандар және дефис. Жарияланғаннан кейін өзгертпеңіз.
   */
  slug: string;
  description?: string | null;
  order: number;
  seo?: {
    /**
     * Ұсыныс: 30–60 таңба. Бос болса, бет атауы қолданылады.
     */
    title?: string | null;
    /**
     * Ұсыныс: 120–160 таңба.
     */
    description?: string | null;
    /**
     * Іздеу жүйелеріне бұл бетті индекстеуге тыйым салу.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  publisher: string;
  url: string;
  sourceType: 'government' | 'legal-act' | 'official-provider' | 'reference';
  trustTier: 'primary-official' | 'official-provider' | 'secondary';
  documentNumber?: string | null;
  publisherUpdatedAt?: string | null;
  language: 'kk' | 'ru' | 'en';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-rule-sets".
 */
export interface CalculatorRuleSet {
  id: number;
  title: string;
  /**
   * Тұрақты URL: латын әріптері, сандар және дефис. Жарияланғаннан кейін өзгертпеңіз.
   */
  slug: string;
  calculatorKey: 'maternity-benefit' | 'childcare-benefit' | 'vehicle-tax' | 'auto-loan' | 'salary';
  /**
   * Мысалы: 2026.1
   */
  version: string;
  effectiveFrom: string;
  effectiveUntil?: string | null;
  /**
   * Кодтағы калькулятор схемасы бұл JSON құрылымын міндетті түрде тексереді.
   */
  parameters:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Осы материалдағы нақты тұжырымдарды растайтын дереккөздер.
   */
  sourceReferences: {
    source: number | Source;
    isPrimary?: boolean | null;
    claimsSupported: string;
    evidenceSummary?: string | null;
    checkedAt: string;
    validFrom?: string | null;
    validUntil?: string | null;
    id?: string | null;
  }[];
  verification: {
    status: 'unverified' | 'in-review' | 'verified' | 'stale';
    riskLevel: 'high' | 'medium' | 'low';
    reviewedAt?: string | null;
    reviewedBy?: (number | null) | User;
    nextReviewAt?: string | null;
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios".
 */
export interface Scenario {
  id: number;
  title: string;
  /**
   * Тұрақты URL: латын әріптері, сандар және дефис. Жарияланғаннан кейін өзгертпеңіз.
   */
  slug: string;
  publishedSlug?: string | null;
  category: number | Category;
  /**
   * Пайдаланушы бірінші экранда көретін қысқа жауап.
   */
  shortAnswer: string;
  whoIsItFor: string;
  eligibility?:
    | {
        condition: string;
        explanation?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        name: string;
        note?: string | null;
        optional?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cost: {
    kind: 'free' | 'fixed' | 'range' | 'calculated' | 'varies';
    amount?: number | null;
    minAmount?: number | null;
    maxAmount?: number | null;
    explanation?: string | null;
    asOf?: string | null;
  };
  processingTime?: {
    value?: string | null;
    explanation?: string | null;
  };
  steps: {
    title: string;
    description: string;
    actionLabel?: string | null;
    actionUrl?: string | null;
    id?: string | null;
  }[];
  officialLinks: {
    label: string;
    url: string;
    publisher: string;
    id?: string | null;
  }[];
  calculatorRuleSet?: (number | null) | CalculatorRuleSet;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedScenarios?: (number | Scenario)[] | null;
  /**
   * Осы материалдағы нақты тұжырымдарды растайтын дереккөздер.
   */
  sourceReferences: {
    source: number | Source;
    isPrimary?: boolean | null;
    claimsSupported: string;
    evidenceSummary?: string | null;
    checkedAt: string;
    validFrom?: string | null;
    validUntil?: string | null;
    id?: string | null;
  }[];
  verification: {
    status: 'unverified' | 'in-review' | 'verified' | 'stale';
    riskLevel: 'high' | 'medium' | 'low';
    reviewedAt?: string | null;
    reviewedBy?: (number | null) | User;
    nextReviewAt?: string | null;
    notes?: string | null;
  };
  seo?: {
    /**
     * Ұсыныс: 30–60 таңба. Бос болса, бет атауы қолданылады.
     */
    title?: string | null;
    /**
     * Ұсыныс: 120–160 таңба.
     */
    description?: string | null;
    /**
     * Іздеу жүйелеріне бұл бетті индекстеуге тыйым салу.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'calculator-rule-sets';
        value: number | CalculatorRuleSet;
      } | null)
    | ({
        relationTo: 'scenarios';
        value: number | Scenario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  publisher?: T;
  url?: T;
  sourceType?: T;
  trustTier?: T;
  documentNumber?: T;
  publisherUpdatedAt?: T;
  language?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-rule-sets_select".
 */
export interface CalculatorRuleSetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  calculatorKey?: T;
  version?: T;
  effectiveFrom?: T;
  effectiveUntil?: T;
  parameters?: T;
  sourceReferences?:
    | T
    | {
        source?: T;
        isPrimary?: T;
        claimsSupported?: T;
        evidenceSummary?: T;
        checkedAt?: T;
        validFrom?: T;
        validUntil?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        status?: T;
        riskLevel?: T;
        reviewedAt?: T;
        reviewedBy?: T;
        nextReviewAt?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios_select".
 */
export interface ScenariosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedSlug?: T;
  category?: T;
  shortAnswer?: T;
  whoIsItFor?: T;
  eligibility?:
    | T
    | {
        condition?: T;
        explanation?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        name?: T;
        note?: T;
        optional?: T;
        id?: T;
      };
  cost?:
    | T
    | {
        kind?: T;
        amount?: T;
        minAmount?: T;
        maxAmount?: T;
        explanation?: T;
        asOf?: T;
      };
  processingTime?:
    | T
    | {
        value?: T;
        explanation?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        actionLabel?: T;
        actionUrl?: T;
        id?: T;
      };
  officialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        publisher?: T;
        id?: T;
      };
  calculatorRuleSet?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedScenarios?: T;
  sourceReferences?:
    | T
    | {
        source?: T;
        isPrimary?: T;
        claimsSupported?: T;
        evidenceSummary?: T;
        checkedAt?: T;
        validFrom?: T;
        validUntil?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        status?: T;
        riskLevel?: T;
        reviewedAt?: T;
        reviewedBy?: T;
        nextReviewAt?: T;
        notes?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  defaultSeoDescription?: string | null;
  /**
   * Ішкі байланыс. Ашық бетте автоматты түрде көрсетілмейді.
   */
  editorialContact?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  defaultSeoDescription?: T;
  editorialContact?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}